//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Local
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalEntities : DbContext
    {
        public LocalEntities()
            : base("name=LocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<School_Attendance> School_Attendance { get; set; }
        public virtual DbSet<School_AttendanceSession> School_AttendanceSession { get; set; }
        public virtual DbSet<Student_ProfileData> Student_ProfileData { get; set; }
        public virtual DbSet<System_Setting> System_Setting { get; set; }
    }
}
