//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_Attendance
    {
        public long Id { get; set; }
        public string StudentMatricNumber { get; set; }
        public string StudentTagId { get; set; }
        public System.DateTime DateRecorded { get; set; }
        public long AttendanceSessionId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
