//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Local
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_AttendanceSession
    {
        public long Id { get; set; }
        public int CourseId { get; set; }
        public int AcademicPeriodId { get; set; }
        public int AttendanceFunctionId { get; set; }
        public string AttendanceDescription { get; set; }
        public System.DateTime DateRecorded { get; set; }
        public int UserRecorded { get; set; }
        public bool IsUploaded { get; set; }
        public bool IsDeleted { get; set; }
        public string AttendanceSessionGuid { get; set; }
    }
}
