//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_AccessCredential
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string PasswordData { get; set; }
        public string PasswordSalt { get; set; }
        public bool IsDeleted { get; set; }
    }
}
