//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_RegistrationSessionManifestItems
    {
        public long Id { get; set; }
        public int RegistrationSessionManifestId { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public string DataPayLoad { get; set; }
        public bool IsDeleted { get; set; }
    }
}
