//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_ProfileData
    {
        public int Id { get; set; }
        public string MatricNumber { get; set; }
        public string TagId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Picture { get; set; }
        public bool IsDeleted { get; set; }
        public string BloodGroup { get; set; }
    }
}
