//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBoxPremium.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_CourseRegistration
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int AcademicPeriodId { get; set; }
        public int StudentId { get; set; }
        public int SchoolIdId { get; set; }
        public int SubSchoolId { get; set; }
        public int SubSchoolDepartmentId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
